version: '3.8'
services:
  migrations:
    image: flyway/flyway:8.5.11-alpine
    command: -url=jdbc:postgresql://db:${DB_PORT}/${DB_NAME} -user=${DB_USER} -password=${DB_PW} -connectRetries=10 migrate info
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
    volumes:
      - db:/data/postgres

volumes:
  db:
